// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Arpit Bhatnagar",
            "email": "arpitbhatnagar10@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Check server's health",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Server's health-check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/v1/data/refresh": {
            "post": {
                "description": "Fetches and persists India's covid 19 data in DB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "covidApi"
                ],
                "summary": "Populate Covid19 Data",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DataIngestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/geo": {
            "get": {
                "description": "Get India \u0026 State's covid data based on geo-location",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "covidApi"
                ],
                "summary": "Get Covid Data for State",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Latitude",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude",
                        "name": "lng",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.UserFeedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CovidRegionResponse": {
            "type": "object",
            "properties": {
                "activeCases": {
                    "description": "Total Active Cases",
                    "type": "string",
                    "example": "0"
                },
                "confirmedCases": {
                    "description": "Total Confirmed Cases",
                    "type": "string",
                    "example": "0"
                },
                "deaths": {
                    "description": "Total Deaths",
                    "type": "string",
                    "example": "0"
                },
                "recovered": {
                    "description": "Total Recovered",
                    "type": "string",
                    "example": "0"
                },
                "region": {
                    "description": "Data Region",
                    "type": "string"
                },
                "remoteSyncTime": {
                    "description": "Instant at which data was updated by 3rd Party Data Provider",
                    "type": "string"
                }
            }
        },
        "models.DataIngestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Success Message",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Data Updated At",
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Error Message",
                    "type": "string"
                },
                "status": {
                    "description": "Error",
                    "type": "string"
                }
            }
        },
        "models.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status of server",
                    "type": "string"
                }
            }
        },
        "models.UserFeedResponse": {
            "type": "object",
            "properties": {
                "india": {
                    "description": "India's covid data",
                    "$ref": "#/definitions/models.CovidRegionResponse"
                },
                "last_updated_at": {
                    "description": "Data last updated at",
                    "type": "string"
                },
                "state": {
                    "description": "State's covid data",
                    "$ref": "#/definitions/models.CovidRegionResponse"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8000",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Covid 19 API Server",
	Description: "Get covid data based on your geo-location in India",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
