basePath: /
definitions:
  models.CovidRegionResponse:
    properties:
      activeCases:
        description: Total Active Cases
        example: "0"
        type: string
      confirmedCases:
        description: Total Confirmed Cases
        example: "0"
        type: string
      deaths:
        description: Total Deaths
        example: "0"
        type: string
      recovered:
        description: Total Recovered
        example: "0"
        type: string
    type: object
  models.ErrorResponse:
    properties:
      message:
        description: Error Message
        type: string
      status:
        description: Status
        type: string
    type: object
  models.GeoCovidDataResponse:
    properties:
      india:
        $ref: '#/definitions/models.CovidRegionResponse'
        description: India's covid data
      last_updated_at:
        description: Data last updated at
        type: string
      state:
        $ref: '#/definitions/models.CovidRegionResponse'
        description: State's covid data
    type: object
  models.SimpleMessageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: arpitbhatnagar10@gmail.com
    name: Arpit Bhatnagar
  description: Get covid data based on your geo-location in India
  title: Covid 19 API Server
  version: "1.0"
paths:
  /healthcheck:
    get:
      description: Check server's health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SimpleMessageResponse'
      summary: Server's health-check
      tags:
      - healthcheck
  /v1/covid/geo:
    get:
      description: Get India & State's covid data based on geo-location
      parameters:
      - description: Latitude
        in: query
        maximum: 90
        minimum: -90
        name: lat
        required: true
        type: number
      - description: Longitude
        in: query
        maximum: 180
        minimum: -180
        name: lng
        required: true
        type: number
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.GeoCovidDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get Covid Data for State
      tags:
      - covidApi
  /v1/covid/refresh:
    post:
      description: Fetches and persists India's covid 19 data in DB
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SimpleMessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Populate Covid19 Data
      tags:
      - covidApi
swagger: "2.0"
